#!/usr/bin/env bash
# warpi install.sh — install a packaged warpi bundle (Linux or macOS).
#
# Runs entirely as the current user: no sudo, no network. Override the target
# locations with environment variables:
#
#   WARPI_INSTALL_PREFIX   install root            (default: ~/.local/opt/warpi)
#   WARPI_BIN_DIR          launcher directory      (default: ~/.local/bin)
#   WARPI_FORCE=1          replace a foreign launcher at $WARPI_BIN_DIR/warpi
#
# The bundle must already contain a built helper at
# standalone/pi-helper/dist/main.js (run `npm run build` in standalone/pi-helper
# before packaging). A bundled Node runtime at standalone/node/bin/node is used
# automatically; without one, Node >= 22.19 must be on PATH.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${WARPI_INSTALL_PREFIX:-$HOME/.local/opt/warpi}"
BIN_DIR="${WARPI_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/warpi"
FORCE="${WARPI_FORCE:-0}"

fail() {
    printf 'install.sh: %s\n' "$*" >&2
    exit 1
}

case "${1:-}" in
    -h | --help)
        sed -n '2,15p' "${BASH_SOURCE[0]}"
        exit 0
        ;;
    "") ;;
    *) fail "unknown argument: $1 (try --help)" ;;
esac

[ -x "$SCRIPT_DIR/warpi" ] || fail "bundle is incomplete: $SCRIPT_DIR/warpi is missing or not executable"
[ -f "$SCRIPT_DIR/standalone/pi-helper/dist/main.js" ] \
    || fail "bundle is incomplete: standalone/pi-helper/dist/main.js is missing (build the helper first)"
[ -f "$SCRIPT_DIR/standalone/pi-helper/package.json" ] \
    || fail "bundle is incomplete: standalone/pi-helper/package.json is missing"

# Prefer the bundled runtime; only require a system node when it is absent.
BUNDLED_NODE="$SCRIPT_DIR/standalone/node/bin/node"
if [ -x "$BUNDLED_NODE" ]; then
    NODE_BIN="$BUNDLED_NODE"
else
    NODE_BIN="$(command -v node || true)"
    [ -n "$NODE_BIN" ] || fail "Node.js >= 22.19 is required but neither a bundled runtime nor 'node' on PATH was found"
fi

NODE_REQUIRED="22.19.0"
NODE_HAVE="$("$NODE_BIN" -p 'process.versions.node' 2>/dev/null || true)"
[ -n "$NODE_HAVE" ] || fail "could not determine the Node.js version from $NODE_BIN"
if [ "$(printf '%s\n%s\n' "$NODE_REQUIRED" "$NODE_HAVE" | sort -V | head -n1)" != "$NODE_REQUIRED" ]; then
    fail "Node.js >= $NODE_REQUIRED is required, found $NODE_HAVE"
fi

if [ -e "$LAUNCHER" ] && ! grep -q "Generated by warpi install.sh" "$LAUNCHER" 2>/dev/null; then
    if [ "$FORCE" != "1" ]; then
        fail "$LAUNCHER already exists and was not created by warpi; re-run with WARPI_FORCE=1 to replace it"
    fi
fi

install -d -m 0755 "$PREFIX" "$PREFIX/standalone" "$BIN_DIR"
install -m 0755 "$SCRIPT_DIR/warpi" "$PREFIX/warpi"

rm -rf "$PREFIX/standalone/pi-helper"
mkdir -p "$PREFIX/standalone/pi-helper"
cp -a "$SCRIPT_DIR/standalone/pi-helper/." "$PREFIX/standalone/pi-helper/"

# Bundled Node runtime, if the bundle carries one. The app resolves it relative
# to the executable (standalone/node/bin/node); no environment is needed.
if [ -d "$SCRIPT_DIR/standalone/node" ]; then
    rm -rf "$PREFIX/standalone/node"
    mkdir -p "$PREFIX/standalone/node"
    cp -a "$SCRIPT_DIR/standalone/node/." "$PREFIX/standalone/node/"
fi

shopt -s nullglob
docs=("$SCRIPT_DIR"/standalone/*.md)
shopt -u nullglob
if ((${#docs[@]} > 0)); then
    cp -a "${docs[@]}" "$PREFIX/standalone/"
fi

for name in LICENSE-AGPL LICENSE-MIT LICENSE-NOTES.md THIRD_PARTY_LICENSES.txt config.example.json; do
    [ -e "$SCRIPT_DIR/$name" ] && cp -a "$SCRIPT_DIR/$name" "$PREFIX/$name"
done

cat >"$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by warpi install.sh — do not edit.
set -euo pipefail
WARPI_HOME="\${WARPI_HOME:-$PREFIX}"
if [ ! -x "\$WARPI_HOME/standalone/node/bin/node" ] && ! command -v node >/dev/null 2>&1; then
    echo "warpi: Node.js >= 22.19 is required (no bundled runtime and 'node' not on PATH)." >&2
    exit 1
fi
export WARPI_PI_HELPER_ENTRY="\${WARPI_PI_HELPER_ENTRY:-\$WARPI_HOME/standalone/pi-helper/dist/main.js}"
exec "\$WARPI_HOME/warpi" "\$@"
EOF
chmod 0755 "$LAUNCHER"

# Linux desktop entry + hicolor icons. Best-effort and Linux-only; macOS uses
# the .app bundle instead.
if [ "$(uname -s)" = "Linux" ]; then
    DESKTOP_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
    DESKTOP_SRC="$SCRIPT_DIR/share/applications/dev.warpi.Warpi.desktop"
    if [ -f "$DESKTOP_SRC" ]; then
        install -d -m 0755 "$DESKTOP_HOME/applications"
        sed "s|^Exec=warpi |Exec=$LAUNCHER |" "$DESKTOP_SRC" \
            >"$DESKTOP_HOME/applications/dev.warpi.Warpi.desktop"
        for size in 16x16 32x32 48x48 64x64 128x128 256x256 512x512; do
            icon="$SCRIPT_DIR/share/icons/hicolor/$size/apps/dev.warpi.Warpi.png"
            if [ -f "$icon" ]; then
                install -Dm644 "$icon" "$DESKTOP_HOME/icons/hicolor/$size/apps/dev.warpi.Warpi.png"
            fi
        done
        command -v update-desktop-database >/dev/null 2>&1 \
            && update-desktop-database "$DESKTOP_HOME/applications" >/dev/null 2>&1 || true
        command -v gtk-update-icon-cache >/dev/null 2>&1 \
            && gtk-update-icon-cache -q -t -f "$DESKTOP_HOME/icons/hicolor" >/dev/null 2>&1 || true
    fi
fi

printf 'warpi installed:\n'
printf '  binary:   %s\n' "$PREFIX/warpi"
printf '  helper:   %s\n' "$PREFIX/standalone/pi-helper/dist/main.js"
printf '  node:     %s\n' "$( [ -x "$PREFIX/standalone/node/bin/node" ] && echo "$PREFIX/standalone/node/bin/node (bundled)" || echo "$NODE_BIN (system)" )"
printf '  launcher: %s\n' "$LAUNCHER"
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) printf '\nNote: %s is not on your PATH; add it to run `warpi` by name.\n' "$BIN_DIR" ;;
esac
printf '\nConfigure a provider in Settings → Agents → Local Pi provider, or edit\n'
printf 'the standalone config.json under the warpi data directory (see config.example.json).\n'
